const starship = [
  {
      "id": "1",
      "consumables": "1 year",
      "name": "CR90 corvette",
      "cargo_capacity": "3000000",
      "passengers": "600",
      "max_atmosphering_speed": "950",
      "crew": "30-165",
      "length": "150",
      "model": "CR90 corvette",
      "cost_in_credits": "3500000",
      "manufacturer": "Corellian Engineering Corporation"
  },
  {
      "id": "2",
      "consumables": "2 years",
      "name": "Star Destroyer",
      "cargo_capacity": "36000000",
      "passengers": "n/a",
      "max_atmosphering_speed": "975",
      "crew": "47,060",
      "length": "1,600",
      "model": "Imperial I-class Star Destroyer",
      "cost_in_credits": "150000000",
      "manufacturer": "Kuat Drive Yards"
  },
  {
      "id": "3",
      "consumables": "2 months",
      "name": "Sand Crawler",
      "cargo_capacity": "50000",
      "passengers": "30",
      "max_atmosphering_speed": "30",
      "crew": "46",
      "length": "36.8 ",
      "model": "Digger Crawler",
      "cost_in_credits": "150000",
      "manufacturer": "Corellia Mining Corporation"
  },
  {
      "id": "4",
      "consumables": "1 month",
      "name": "Sentinel-class landing craft",
      "cargo_capacity": "180000",
      "passengers": "75",
      "max_atmosphering_speed": "1000",
      "crew": "5",
      "length": "38",
      "model": "Sentinel-class landing craft",
      "cost_in_credits": "240000",
      "manufacturer": "Sienar Fleet Systems, Cyngus Spaceworks"
  },
  {
      "id": "5",
      "consumables": "0",
      "name": "T-16 skyhopper",
      "cargo_capacity": "50",
      "passengers": "1",
      "max_atmosphering_speed": "1200",
      "crew": "1",
      "length": "10.4 ",
      "model": "T-16 skyhopper",
      "cost_in_credits": "14500",
      "manufacturer": "Incom Corporation"
  },
  {
      "id": "6",
      "consumables": "unknown",
      "name": "X-34 landspeeder",
      "cargo_capacity": "5",
      "passengers": "1",
      "max_atmosphering_speed": "250",
      "crew": "1",
      "length": "3.4 ",
      "model": "X-34 landspeeder",
      "cost_in_credits": "10550",
      "manufacturer": "SoroSuub Corporation"
  },
  {
      "id": "7",
      "consumables": "2 days",
      "name": "TIE/LN starfighter",
      "cargo_capacity": "65",
      "passengers": "0",
      "max_atmosphering_speed": "1200",
      "crew": "1",
      "length": "6.4",
      "model": "Twin Ion Engine/Ln Starfighter",
      "cost_in_credits": "unknown",
      "manufacturer": "Sienar Fleet Systems"
  },
  {
      "id": "8",
      "consumables": "3 years",
      "name": "Death Star",
      "cargo_capacity": "1000000000000",
      "passengers": "843,342",
      "max_atmosphering_speed": "n/a",
      "crew": "342,953",
      "length": "120000",
      "model": "DS-1 Orbital Battle Station",
      "cost_in_credits": "1000000000000",
      "manufacturer": "Imperial Department of Military Research, Sienar Fleet Systems"
  },
  {
      "id": "9",
      "consumables": "2 months",
      "name": "Millennium Falcon",
      "cargo_capacity": "100000",
      "passengers": "6",
      "max_atmosphering_speed": "1050",
      "crew": "4",
      "length": "34.37",
      "model": "YT-1300 light freighter",
      "cost_in_credits": "100000",
      "manufacturer": "Corellian Engineering Corporation"
  },
  {
      "id": "10",
      "consumables": "1 week",
      "name": "Y-wing",
      "cargo_capacity": "110",
      "passengers": "0",
      "max_atmosphering_speed": "1000km",
      "crew": "2",
      "length": "14",
      "model": "BTL Y-wing",
      "cost_in_credits": "134999",
      "manufacturer": "Koensayr Manufacturing"
  },
  {
      "id": "11",
      "consumables": "1 week",
      "name": "X-wing",
      "cargo_capacity": "110",
      "passengers": "0",
      "max_atmosphering_speed": "1050",
      "crew": "1",
      "length": "12.5",
      "model": "T-65 X-wing",
      "cost_in_credits": "149999",
      "manufacturer": "Incom Corporation"
  },
  {
      "id": "12",
      "consumables": "5 days",
      "name": "TIE Advanced x1",
      "cargo_capacity": "150",
      "passengers": "0",
      "max_atmosphering_speed": "1200",
      "crew": "1",
      "length": "9.2",
      "model": "Twin Ion Engine Advanced x1",
      "cost_in_credits": "unknown",
      "manufacturer": "Sienar Fleet Systems"
  },
  {
      "id": "13",
      "consumables": "none",
      "name": "Snowspeeder",
      "cargo_capacity": "10",
      "passengers": "0",
      "max_atmosphering_speed": "650",
      "crew": "2",
      "length": "4.5",
      "model": "t-47 airspeeder",
      "cost_in_credits": "unknown",
      "manufacturer": "Incom corporation"
  },
  {
      "id": "14",
      "consumables": "6 years",
      "name": "Executor",
      "cargo_capacity": "250000000",
      "passengers": "38000",
      "max_atmosphering_speed": "n/a",
      "crew": "279,144",
      "length": "19000",
      "model": "Executor-class star dreadnought",
      "cost_in_credits": "1143350000",
      "manufacturer": "Kuat Drive Yards, Fondor Shipyards"
  },
  {
      "id": "15",
      "consumables": "2 days",
      "name": "TIE bomber",
      "cargo_capacity": "none",
      "passengers": "0",
      "max_atmosphering_speed": "850",
      "crew": "1",
      "length": "7.8",
      "model": "TIE/sa bomber",
      "cost_in_credits": "unknown",
      "manufacturer": "Sienar Fleet Systems"
  },
  {
      "id": "16",
      "consumables": "6 months",
      "name": "Rebel transport",
      "cargo_capacity": "19000000",
      "passengers": "90",
      "max_atmosphering_speed": "650",
      "crew": "6",
      "length": "90",
      "model": "GR-75 medium transport",
      "cost_in_credits": "unknown",
      "manufacturer": "Gallofree Yards, Inc."
  },
  {
      "id": "17",
      "consumables": "unknown",
      "name": "AT-AT",
      "cargo_capacity": "1000",
      "passengers": "40",
      "max_atmosphering_speed": "60",
      "crew": "5",
      "length": "20",
      "model": "All Terrain Armored Transport",
      "cost_in_credits": "unknown",
      "manufacturer": "Kuat Drive Yards, Imperial Department of Military Research"
  },
  {
      "id": "18",
      "consumables": "none",
      "name": "AT-ST",
      "cargo_capacity": "200",
      "passengers": "0",
      "max_atmosphering_speed": "90",
      "crew": "2",
      "length": "2",
      "model": "All Terrain Scout Transport",
      "cost_in_credits": "unknown",
      "manufacturer": "Kuat Drive Yards, Imperial Department of Military Research"
  },
  {
      "id": "19",
      "consumables": "1 day",
      "name": "Storm IV Twin-Pod cloud car",
      "cargo_capacity": "10",
      "passengers": "0",
      "max_atmosphering_speed": "1500",
      "crew": "2",
      "length": "7",
      "model": "Storm IV Twin-Pod",
      "cost_in_credits": "75000",
      "manufacturer": "Bespin Motors"
  },
  {
      "id": "20",
      "consumables": "1 month",
      "name": "Slave 1",
      "cargo_capacity": "70000",
      "passengers": "6",
      "max_atmosphering_speed": "1000",
      "crew": "1",
      "length": "21.5",
      "model": "Firespray-31-class patrol and attack",
      "cost_in_credits": "unknown",
      "manufacturer": "Kuat Systems Engineering"
  },
  {
      "id": "21",
      "consumables": "2 months",
      "name": "Imperial shuttle",
      "cargo_capacity": "80000",
      "passengers": "20",
      "max_atmosphering_speed": "850",
      "crew": "6",
      "length": "20",
      "model": "Lambda-class T-4a shuttle",
      "cost_in_credits": "240000",
      "manufacturer": "Sienar Fleet Systems"
  },
  {
      "id": "22",
      "consumables": "2 years",
      "name": "EF76 Nebulon-B escort frigate",
      "cargo_capacity": "6000000",
      "passengers": "75",
      "max_atmosphering_speed": "800",
      "crew": "854",
      "length": "300",
      "model": "EF76 Nebulon-B escort frigate",
      "cost_in_credits": "8500000",
      "manufacturer": "Kuat Drive Yards"
  },
  {
      "id": "23",
      "consumables": "Live food tanks",
      "name": "Sail barge",
      "cargo_capacity": "2000000",
      "passengers": "500",
      "max_atmosphering_speed": "100",
      "crew": "26",
      "length": "30",
      "model": "Modified Luxury Sail Barge",
      "cost_in_credits": "285000",
      "manufacturer": "Ubrikkian Industries Custom Vehicle Division"
  },
  {
      "id": "24",
      "consumables": "1 day",
      "name": "Bantha-II cargo skiff",
      "cargo_capacity": "135000",
      "passengers": "16",
      "max_atmosphering_speed": "250",
      "crew": "5",
      "length": "9.5",
      "model": "Bantha-II",
      "cost_in_credits": "8000",
      "manufacturer": "Ubrikkian Industries"
  },
  {
      "id": "25",
      "consumables": "2 days",
      "name": "TIE/IN interceptor",
      "cargo_capacity": "75",
      "passengers": "0",
      "max_atmosphering_speed": "1250",
      "crew": "1",
      "length": "9.6",
      "model": "Twin Ion Engine Interceptor",
      "cost_in_credits": "unknown",
      "manufacturer": "Sienar Fleet Systems"
  },
  {
      "id": "26",
      "consumables": "2 years",
      "name": "Calamari Cruiser",
      "cargo_capacity": "unknown",
      "passengers": "1200",
      "max_atmosphering_speed": "n/a",
      "crew": "5400",
      "length": "1200",
      "model": "MC80 Liberty type Star Cruiser",
      "cost_in_credits": "104000000",
      "manufacturer": "Mon Calamari shipyards"
  },
  {
      "id": "27",
      "consumables": "1 week",
      "name": "A-wing",
      "cargo_capacity": "40",
      "passengers": "0",
      "max_atmosphering_speed": "1300",
      "crew": "1",
      "length": "9.6",
      "model": "RZ-1 A-wing Interceptor",
      "cost_in_credits": "175000",
      "manufacturer": "Alliance Underground Engineering, Incom Corporation"
  },
  {
      "id": "28",
      "consumables": "1 week",
      "name": "B-wing",
      "cargo_capacity": "45",
      "passengers": "0",
      "max_atmosphering_speed": "950",
      "crew": "1",
      "length": "16.9",
      "model": "A/SF-01 B-wing starfighter",
      "cost_in_credits": "220000",
      "manufacturer": "Slayn & Korpil"
  },
  {
      "id": "29",
      "consumables": "1 day",
      "name": "Imperial Speeder Bike",
      "cargo_capacity": "4",
      "passengers": "1",
      "max_atmosphering_speed": "360",
      "crew": "1",
      "length": "3",
      "model": "74-Z speeder bike",
      "cost_in_credits": "8000",
      "manufacturer": "Aratech Repulsor Company"
  },
  {
      "id": "30",
      "consumables": "unknown",
      "name": "Republic Cruiser",
      "cargo_capacity": "unknown",
      "passengers": "16",
      "max_atmosphering_speed": "900",
      "crew": "9",
      "length": "115",
      "model": "Consular-class cruiser",
      "cost_in_credits": "unknown",
      "manufacturer": "Corellian Engineering Corporation"
  },
  {
      "id": "31",
      "consumables": "500 days",
      "name": "Droid control ship",
      "cargo_capacity": "4000000000",
      "passengers": "139000",
      "max_atmosphering_speed": "n/a",
      "crew": "175",
      "length": "3170",
      "model": "Lucrehulk-class Droid Control Ship",
      "cost_in_credits": "unknown",
      "manufacturer": "Hoersch-Kessel Drive, Inc."
  },
  {
      "id": "32",
      "consumables": "none",
      "name": "Vulture Droid",
      "cargo_capacity": "0",
      "passengers": "0",
      "max_atmosphering_speed": "1200",
      "crew": "0",
      "length": "3.5",
      "model": "Vulture-class droid starfighter",
      "cost_in_credits": "unknown",
      "manufacturer": "Haor Chall Engineering, Baktoid Armor Workshop"
  },
  {
      "id": "33",
      "consumables": "unknown",
      "name": "Multi-Troop Transport",
      "cargo_capacity": "12000",
      "passengers": "112",
      "max_atmosphering_speed": "35",
      "crew": "4",
      "length": "31",
      "model": "Multi-Troop Transport",
      "cost_in_credits": "138000",
      "manufacturer": "Baktoid Armor Workshop"
  },
  {
      "id": "34",
      "consumables": "unknown",
      "name": "Armored Assault Tank",
      "cargo_capacity": "unknown",
      "passengers": "6",
      "max_atmosphering_speed": "55",
      "crew": "4",
      "length": "9.75",
      "model": "Armoured Assault Tank",
      "cost_in_credits": "unknown",
      "manufacturer": "Baktoid Armor Workshop"
  },
  {
      "id": "35",
      "consumables": "none",
      "name": "Single Trooper Aerial Platform",
      "cargo_capacity": "none",
      "passengers": "0",
      "max_atmosphering_speed": "400",
      "crew": "1",
      "length": "2",
      "model": "Single Trooper Aerial Platform",
      "cost_in_credits": "2500",
      "manufacturer": "Baktoid Armor Workshop"
  },
  {
      "id": "36",
      "consumables": "1 day",
      "name": "C-9979 landing craft",
      "cargo_capacity": "1800000",
      "passengers": "284",
      "max_atmosphering_speed": "587",
      "crew": "140",
      "length": "210",
      "model": "C-9979 landing craft",
      "cost_in_credits": "200000",
      "manufacturer": "Haor Chall Engineering"
  },
  {
      "id": "37",
      "consumables": "unknown",
      "name": "Tribubble bongo",
      "cargo_capacity": "1600",
      "passengers": "2",
      "max_atmosphering_speed": "85",
      "crew": "1",
      "length": "15",
      "model": "Tribubble bongo",
      "cost_in_credits": "unknown",
      "manufacturer": "Otoh Gunga Bongameken Cooperative"
  },
  {
      "id": "38",
      "consumables": "7 days",
      "name": "Naboo fighter",
      "cargo_capacity": "65",
      "passengers": "0",
      "max_atmosphering_speed": "1100",
      "crew": "1",
      "length": "11",
      "model": "N-1 starfighter",
      "cost_in_credits": "200000",
      "manufacturer": "Theed Palace Space Vessel Engineering Corps"
  },
  {
      "id": "39",
      "consumables": "unknown",
      "name": "Naboo Royal Starship",
      "cargo_capacity": "unknown",
      "passengers": "unknown",
      "max_atmosphering_speed": "920",
      "crew": "8",
      "length": "76",
      "model": "J-type 327 Nubian royal starship",
      "cost_in_credits": "unknown",
      "manufacturer": "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives"
  },
  {
      "id": "40",
      "consumables": "30 days",
      "name": "Scimitar",
      "cargo_capacity": "2500000",
      "passengers": "6",
      "max_atmosphering_speed": "1180",
      "crew": "1",
      "length": "26.5",
      "model": "Star Courier",
      "cost_in_credits": "55000000",
      "manufacturer": "Republic Sienar Systems"
  },
  {
      "id": "41",
      "consumables": "unknown",
      "name": "Sith speeder",
      "cargo_capacity": "2",
      "passengers": "0",
      "max_atmosphering_speed": "180",
      "crew": "1",
      "length": "1.5",
      "model": "FC-20 speeder bike",
      "cost_in_credits": "4000",
      "manufacturer": "Razalon"
  },
  {
      "id": "42",
      "consumables": "1 year",
      "name": "J-type diplomatic barge",
      "cargo_capacity": "unknown",
      "passengers": "10",
      "max_atmosphering_speed": "2000",
      "crew": "5",
      "length": "39",
      "model": "J-type diplomatic barge",
      "cost_in_credits": "2000000",
      "manufacturer": "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives"
  },
  {
      "id": "43",
      "consumables": "none",
      "name": "Zephyr-G swoop bike",
      "cargo_capacity": "200",
      "passengers": "1",
      "max_atmosphering_speed": "350",
      "crew": "1",
      "length": "3.68",
      "model": "Zephyr-G swoop bike",
      "cost_in_credits": "5750",
      "manufacturer": "Mobquet Swoops and Speeders"
  },
  {
      "id": "44",
      "consumables": "unknown",
      "name": "Koro-2 Exodrive airspeeder",
      "cargo_capacity": "80",
      "passengers": "1",
      "max_atmosphering_speed": "800",
      "crew": "1",
      "length": "6.6",
      "model": "Koro-2 Exodrive airspeeder",
      "cost_in_credits": "unknown",
      "manufacturer": "Desler Gizh Outworld Mobility Corporation"
  },
  {
      "id": "45",
      "consumables": "unknown",
      "name": "XJ-6 airspeeder",
      "cargo_capacity": "unknown",
      "passengers": "1",
      "max_atmosphering_speed": "720",
      "crew": "1",
      "length": "6.23",
      "model": "XJ-6 airspeeder",
      "cost_in_credits": "unknown",
      "manufacturer": "Narglatch AirTech prefabricated kit"
  },
  {
      "id": "46",
      "consumables": "unknown",
      "name": "AA-9 Coruscant freighter",
      "cargo_capacity": "unknown",
      "passengers": "30000",
      "max_atmosphering_speed": "unknown",
      "crew": "unknown",
      "length": "390",
      "model": "Botajef AA-9 Freighter-Liner",
      "cost_in_credits": "unknown",
      "manufacturer": "Botajef Shipyards"
  },
  {
      "id": "47",
      "consumables": "7 days",
      "name": "Jedi starfighter",
      "cargo_capacity": "60",
      "passengers": "0",
      "max_atmosphering_speed": "1150",
      "crew": "1",
      "length": "8",
      "model": "Delta-7 Aethersprite-class interceptor",
      "cost_in_credits": "180000",
      "manufacturer": "Kuat Systems Engineering"
  },
  {
      "id": "48",
      "consumables": "unknown",
      "name": "H-type Nubian yacht",
      "cargo_capacity": "unknown",
      "passengers": "unknown",
      "max_atmosphering_speed": "8000",
      "crew": "4",
      "length": "47.9",
      "model": "H-type Nubian yacht",
      "cost_in_credits": "unknown",
      "manufacturer": "Theed Palace Space Vessel Engineering Corps"
  },
  {
      "id": "49",
      "consumables": "unknown",
      "name": "LAAT/i",
      "cargo_capacity": "170",
      "passengers": "30",
      "max_atmosphering_speed": "620",
      "crew": "6",
      "length": "17.4",
      "model": "Low Altitude Assault Transport/infrantry",
      "cost_in_credits": "unknown",
      "manufacturer": "Rothana Heavy Engineering"
  },
  {
      "id": "50",
      "consumables": "unknown",
      "name": "LAAT/c",
      "cargo_capacity": "40000",
      "passengers": "0",
      "max_atmosphering_speed": "620",
      "crew": "1",
      "length": "28.82",
      "model": "Low Altitude Assault Transport/carrier",
      "cost_in_credits": "unknown",
      "manufacturer": "Rothana Heavy Engineering"
  },
  {
      "id": "51",
      "consumables": "2 years",
      "name": "Republic Assault ship",
      "cargo_capacity": "11250000",
      "passengers": "16000",
      "max_atmosphering_speed": "unknown",
      "crew": "700",
      "length": "752",
      "model": "Acclamator I-class assault ship",
      "cost_in_credits": "unknown",
      "manufacturer": "Rothana Heavy Engineering"
  },
  {
      "id": "52",
      "consumables": "21 days",
      "name": "AT-TE",
      "cargo_capacity": "10000",
      "passengers": "36",
      "max_atmosphering_speed": "60",
      "crew": "6",
      "length": "13.2",
      "model": "All Terrain Tactical Enforcer",
      "cost_in_credits": "unknown",
      "manufacturer": "Rothana Heavy Engineering, Kuat Drive Yards"
  },
  {
      "id": "53",
      "consumables": "7 days",
      "name": "SPHA",
      "cargo_capacity": "500",
      "passengers": "30",
      "max_atmosphering_speed": "35",
      "crew": "25",
      "length": "140",
      "model": "Self-Propelled Heavy Artillery",
      "cost_in_credits": "unknown",
      "manufacturer": "Rothana Heavy Engineering"
  },
  {
      "id": "54",
      "consumables": "unknown",
      "name": "Flitknot speeder",
      "cargo_capacity": "unknown",
      "passengers": "0",
      "max_atmosphering_speed": "634",
      "crew": "1",
      "length": "2",
      "model": "Flitknot speeder",
      "cost_in_credits": "8000",
      "manufacturer": "Huppla Pasa Tisc Shipwrights Collective"
  },
  {
      "id": "55",
      "consumables": "7 days",
      "name": "Neimoidian shuttle",
      "cargo_capacity": "1000",
      "passengers": "6",
      "max_atmosphering_speed": "880",
      "crew": "2",
      "length": "20",
      "model": "Sheathipede-class transport shuttle",
      "cost_in_credits": "unknown",
      "manufacturer": "Haor Chall Engineering"
  },
  {
      "id": "56",
      "consumables": "unknown",
      "name": "Geonosian starfighter",
      "cargo_capacity": "unknown",
      "passengers": "0",
      "max_atmosphering_speed": "20000",
      "crew": "1",
      "length": "9.8",
      "model": "Nantex-class territorial defense",
      "cost_in_credits": "unknown",
      "manufacturer": "Huppla Pasa Tisc Shipwrights Collective"
  },
  {
      "id": "57",
      "consumables": "7 days",
      "name": "Solar Sailer",
      "cargo_capacity": "240",
      "passengers": "11",
      "max_atmosphering_speed": "1600",
      "crew": "3",
      "length": "15.2",
      "model": "Punworcca 116-class interstellar sloop",
      "cost_in_credits": "35700",
      "manufacturer": "Huppla Pasa Tisc Shipwrights Collective"
  },
  {
      "id": "58",
      "consumables": "4 years",
      "name": "Trade Federation cruiser",
      "cargo_capacity": "50000000",
      "passengers": "48247",
      "max_atmosphering_speed": "1050",
      "crew": "600",
      "length": "1088",
      "model": "Providence-class carrier/destroyer",
      "cost_in_credits": "125000000",
      "manufacturer": "Rendili StarDrive, Free Dac Volunteers Engineering corps."
  },
  {
      "id": "59",
      "consumables": "none",
      "name": "Tsmeu-6 personal wheel bike",
      "cargo_capacity": "10",
      "passengers": "1",
      "max_atmosphering_speed": "330",
      "crew": "1",
      "length": "3.5",
      "model": "Tsmeu-6 personal wheel bike",
      "cost_in_credits": "15000",
      "manufacturer": "Z-Gomot Ternbuell Guppat Corporation"
  },
  {
      "id": "60",
      "consumables": "56 days",
      "name": "Theta-class T-2c shuttle",
      "cargo_capacity": "50000",
      "passengers": "16",
      "max_atmosphering_speed": "2000",
      "crew": "5",
      "length": "18.5",
      "model": "Theta-class T-2c shuttle",
      "cost_in_credits": "1000000",
      "manufacturer": "Cygnus Spaceworks"
  },
  {
      "id": "61",
      "consumables": "unknown",
      "name": "Emergency Firespeeder",
      "cargo_capacity": "unknown",
      "passengers": "unknown",
      "max_atmosphering_speed": "unknown",
      "crew": "2",
      "length": "unknown",
      "model": "Fire suppression speeder",
      "cost_in_credits": "unknown",
      "manufacturer": "unknown"
  },
  {
      "id": "62",
      "consumables": "2 years",
      "name": "Republic attack cruiser",
      "cargo_capacity": "20000000",
      "passengers": "2000",
      "max_atmosphering_speed": "975",
      "crew": "7400",
      "length": "1137",
      "model": "Senator-class Star Destroyer",
      "cost_in_credits": "59000000",
      "manufacturer": "Kuat Drive Yards, Allanteen Six shipyards"
  },
  {
      "id": "63",
      "consumables": "unknown",
      "name": "Naboo star skiff",
      "cargo_capacity": "unknown",
      "passengers": "3",
      "max_atmosphering_speed": "1050",
      "crew": "3",
      "length": "29.2",
      "model": "J-type star skiff",
      "cost_in_credits": "unknown",
      "manufacturer": "Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated"
  },
  {
      "id": "64",
      "consumables": "2 days",
      "name": "Jedi Interceptor",
      "cargo_capacity": "60",
      "passengers": "0",
      "max_atmosphering_speed": "1500",
      "crew": "1",
      "length": "5.47",
      "model": "Eta-2 Actis-class light interceptor",
      "cost_in_credits": "320000",
      "manufacturer": "Kuat Systems Engineering"
  },
  {
      "id": "65",
      "consumables": "5 days",
      "name": "arc-170",
      "cargo_capacity": "110",
      "passengers": "0",
      "max_atmosphering_speed": "1000",
      "crew": "3",
      "length": "14.5",
      "model": "Aggressive Reconnaissance-170 starfighte",
      "cost_in_credits": "155000",
      "manufacturer": "Incom Corporation, Subpro Corporation"
  },
  {
      "id": "66",
      "consumables": "none",
      "name": "Droid tri-fighter",
      "cargo_capacity": "0",
      "passengers": "0",
      "max_atmosphering_speed": "1180",
      "crew": "1",
      "length": "5.4",
      "model": "tri-fighter",
      "cost_in_credits": "20000",
      "manufacturer": "Colla Designs, Phlac-Arphocc Automata Industries"
  },
  {
      "id": "67",
      "consumables": "2 years",
      "name": "Banking clan frigte",
      "cargo_capacity": "40000000",
      "passengers": "unknown",
      "max_atmosphering_speed": "unknown",
      "crew": "200",
      "length": "825",
      "model": "Munificent-class star frigate",
      "cost_in_credits": "57000000",
      "manufacturer": "Hoersch-Kessel Drive, Inc, Gwori Revolutionary Industries"
  },
  {
      "id": "68",
      "consumables": "3 days",
      "name": "Oevvaor jet catamaran",
      "cargo_capacity": "50",
      "passengers": "2",
      "max_atmosphering_speed": "420",
      "crew": "2",
      "length": "15.1",
      "model": "Oevvaor jet catamaran",
      "cost_in_credits": "12125",
      "manufacturer": "Appazanna Engineering Works"
  },
  {
      "id": "69",
      "consumables": "none",
      "name": "Raddaugh Gnasp fluttercraft",
      "cargo_capacity": "20",
      "passengers": "0",
      "max_atmosphering_speed": "310",
      "crew": "2",
      "length": "7",
      "model": "Raddaugh Gnasp fluttercraft",
      "cost_in_credits": "14750",
      "manufacturer": "Appazanna Engineering Works"
  },
  {
      "id": "70",
      "consumables": "20 days",
      "name": "Clone turbo tank",
      "cargo_capacity": "30000",
      "passengers": "300",
      "max_atmosphering_speed": "160",
      "crew": "20",
      "length": "49.4",
      "model": "HAVw A6 Juggernaut",
      "cost_in_credits": "350000",
      "manufacturer": "Kuat Drive Yards"
  },
  {
      "id": "71",
      "consumables": "none",
      "name": "Corporate Alliance tank droid",
      "cargo_capacity": "none",
      "passengers": "4",
      "max_atmosphering_speed": "100",
      "crew": "0",
      "length": "10.96",
      "model": "NR-N99 Persuader-class droid enforcer",
      "cost_in_credits": "49000",
      "manufacturer": "Techno Union"
  },
  {
      "id": "72",
      "consumables": "none",
      "name": "Droid gunship",
      "cargo_capacity": "0",
      "passengers": "0",
      "max_atmosphering_speed": "820",
      "crew": "0",
      "length": "12.3",
      "model": "HMP droid gunship",
      "cost_in_credits": "60000",
      "manufacturer": "Baktoid Fleet Ordnance, Haor Chall Engineering"
  },
  {
      "id": "73",
      "consumables": "7 days",
      "name": "Belbullab-22 starfighter",
      "cargo_capacity": "140",
      "passengers": "0",
      "max_atmosphering_speed": "1100",
      "crew": "1",
      "length": "6.71",
      "model": "Belbullab-22 starfighter",
      "cost_in_credits": "168000",
      "manufacturer": "Feethan Ottraw Scalable Assemblies"
  },
  {
      "id": "74",
      "consumables": "15 hours",
      "name": "V-wing",
      "cargo_capacity": "60",
      "passengers": "0",
      "max_atmosphering_speed": "1050",
      "crew": "1",
      "length": "7.9",
      "model": "Alpha-3 Nimbus-class V-wing starfighter",
      "cost_in_credits": "102500",
      "manufacturer": "Kuat Systems Engineering"
  },
  {
      "id": "75",
      "consumables": "1 day",
      "name": "AT-RT",
      "cargo_capacity": "20",
      "passengers": "0",
      "max_atmosphering_speed": "90",
      "crew": "1",
      "length": "3.2",
      "model": "All Terrain Recon Transport",
      "cost_in_credits": "40000",
      "manufacturer": "Kuat Drive Yards"
  }
];

const people = [
  {
      "id": "1",
      "name": "Luke Skywalker",
      "height": "172",
      "mass": "77",
      "hair_color": "blond",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "19BBY",
      "gender": "male",
      "planet": 1
  },
  {
      "id": "2",
      "name": "C-3PO",
      "height": "167",
      "mass": "75",
      "hair_color": "n/a",
      "skin_color": "gold",
      "eye_color": "yellow",
      "birth_year": "112BBY",
      "gender": "n/a",
      "planet": 1
  },
  {
      "id": "3",
      "name": "R2-D2",
      "height": "96",
      "mass": "32",
      "hair_color": "n/a",
      "skin_color": "white, blue",
      "eye_color": "red",
      "birth_year": "33BBY",
      "gender": "n/a",
      "planet": 8
  },
  {
      "id": "4",
      "name": "Darth Vader",
      "height": "202",
      "mass": "136",
      "hair_color": "none",
      "skin_color": "white",
      "eye_color": "yellow",
      "birth_year": "41.9BBY",
      "gender": "male",
      "planet": 1
  },
  {
      "id": "5",
      "name": "Leia Organa",
      "height": "150",
      "mass": "49",
      "hair_color": "brown",
      "skin_color": "light",
      "eye_color": "brown",
      "birth_year": "19BBY",
      "gender": "female",
      "planet": 2
  },
  {
      "id": "6",
      "name": "Owen Lars",
      "height": "178",
      "mass": "120",
      "hair_color": "brown, grey",
      "skin_color": "light",
      "eye_color": "blue",
      "birth_year": "52BBY",
      "gender": "male",
      "planet": 1
  },
  {
      "id": "7",
      "name": "Beru Whitesun lars",
      "height": "165",
      "mass": "75",
      "hair_color": "brown",
      "skin_color": "light",
      "eye_color": "blue",
      "birth_year": "47BBY",
      "gender": "female",
      "planet": 1
  },
  {
      "id": "8",
      "name": "R5-D4",
      "height": "97",
      "mass": "32",
      "hair_color": "n/a",
      "skin_color": "white, red",
      "eye_color": "red",
      "birth_year": "unknown",
      "gender": "n/a",
      "planet": 1
  },
  {
      "id": "9",
      "name": "Biggs Darklighter",
      "height": "183",
      "mass": "84",
      "hair_color": "black",
      "skin_color": "light",
      "eye_color": "brown",
      "birth_year": "24BBY",
      "gender": "male",
      "planet": 1
  },
  {
      "id": "10",
      "name": "Obi-Wan Kenobi",
      "height": "182",
      "mass": "77",
      "hair_color": "auburn, white",
      "skin_color": "fair",
      "eye_color": "blue-gray",
      "birth_year": "57BBY",
      "gender": "male",
      "planet": 20
  },
  {
      "id": "11",
      "name": "Anakin Skywalker",
      "height": "188",
      "mass": "84",
      "hair_color": "blond",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "41.9BBY",
      "gender": "male",
      "planet": 1
  },
  {
      "id": "12",
      "name": "Wilhuff Tarkin",
      "height": "180",
      "mass": "unknown",
      "hair_color": "auburn, grey",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "64BBY",
      "gender": "male",
      "planet": 21
  },
  {
      "id": "13",
      "name": "Chewbacca",
      "height": "228",
      "mass": "112",
      "hair_color": "brown",
      "skin_color": "unknown",
      "eye_color": "blue",
      "birth_year": "200BBY",
      "gender": "male",
      "planet": 14
  },
  {
      "id": "14",
      "name": "Han Solo",
      "height": "180",
      "mass": "80",
      "hair_color": "brown",
      "skin_color": "fair",
      "eye_color": "brown",
      "birth_year": "29BBY",
      "gender": "male",
      "planet": 22
  },
  {
      "id": "15",
      "name": "Greedo",
      "height": "173",
      "mass": "74",
      "hair_color": "n/a",
      "skin_color": "green",
      "eye_color": "black",
      "birth_year": "44BBY",
      "gender": "male",
      "planet": 23
  },
  {
      "id": "16",
      "name": "Jabba Desilijic Tiure",
      "height": "175",
      "mass": "1,358",
      "hair_color": "n/a",
      "skin_color": "green-tan, brown",
      "eye_color": "orange",
      "birth_year": "600BBY",
      "gender": "hermaphrodite",
      "planet": 24
  },
  {
      "id": "17",
      "name": "Wedge Antilles",
      "height": "170",
      "mass": "77",
      "hair_color": "brown",
      "skin_color": "fair",
      "eye_color": "hazel",
      "birth_year": "21BBY",
      "gender": "male",
      "planet": 22
  },
  {
      "id": "18",
      "name": "Jek Tono Porkins",
      "height": "180",
      "mass": "110",
      "hair_color": "brown",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 26
  },
  {
      "id": "19",
      "name": "Yoda",
      "height": "66",
      "mass": "17",
      "hair_color": "white",
      "skin_color": "green",
      "eye_color": "brown",
      "birth_year": "896BBY",
      "gender": "male",
      "planet": 28
  },
  {
      "id": "20",
      "name": "Palpatine",
      "height": "170",
      "mass": "75",
      "hair_color": "grey",
      "skin_color": "pale",
      "eye_color": "yellow",
      "birth_year": "82BBY",
      "gender": "male",
      "planet": 8
  },
  {
      "id": "21",
      "name": "Boba Fett",
      "height": "183",
      "mass": "78.2",
      "hair_color": "black",
      "skin_color": "fair",
      "eye_color": "brown",
      "birth_year": "31.5BBY",
      "gender": "male",
      "planet": 10
  },
  {
      "id": "22",
      "name": "IG-88",
      "height": "200",
      "mass": "140",
      "hair_color": "none",
      "skin_color": "metal",
      "eye_color": "red",
      "birth_year": "15BBY",
      "gender": "none",
      "planet": 28
  },
  {
      "id": "23",
      "name": "Bossk",
      "height": "190",
      "mass": "113",
      "hair_color": "none",
      "skin_color": "green",
      "eye_color": "red",
      "birth_year": "53BBY",
      "gender": "male",
      "planet": 29
  },
  {
      "id": "24",
      "name": "Lando Calrissian",
      "height": "177",
      "mass": "79",
      "hair_color": "black",
      "skin_color": "dark",
      "eye_color": "brown",
      "birth_year": "31BBY",
      "gender": "male",
      "planet": 30
  },
  {
      "id": "25",
      "name": "Lobot",
      "height": "175",
      "mass": "79",
      "hair_color": "none",
      "skin_color": "light",
      "eye_color": "blue",
      "birth_year": "37BBY",
      "gender": "male",
      "planet": 6
  },
  {
      "id": "26",
      "name": "Ackbar",
      "height": "180",
      "mass": "83",
      "hair_color": "none",
      "skin_color": "brown mottle",
      "eye_color": "orange",
      "birth_year": "41BBY",
      "gender": "male",
      "planet": 31
  },
  {
      "id": "27",
      "name": "Mon Mothma",
      "height": "150",
      "mass": "unknown",
      "hair_color": "auburn",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "48BBY",
      "gender": "female",
      "planet": 32
  },
  {
      "id": "28",
      "name": "Arvel Crynyd",
      "height": "unknown",
      "mass": "unknown",
      "hair_color": "brown",
      "skin_color": "fair",
      "eye_color": "brown",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 28
  },
  {
      "id": "29",
      "name": "Wicket Systri Warrick",
      "height": "88",
      "mass": "20",
      "hair_color": "brown",
      "skin_color": "brown",
      "eye_color": "brown",
      "birth_year": "8BBY",
      "gender": "male",
      "planet": 7
  },
  {
      "id": "30",
      "name": "Nien Nunb",
      "height": "160",
      "mass": "68",
      "hair_color": "none",
      "skin_color": "grey",
      "eye_color": "black",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 33
  },
  {
      "id": "31",
      "name": "Qui-Gon Jinn",
      "height": "193",
      "mass": "89",
      "hair_color": "brown",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "92BBY",
      "gender": "male",
      "planet": 28
  },
  {
      "id": "32",
      "name": "Nute Gunray",
      "height": "191",
      "mass": "90",
      "hair_color": "none",
      "skin_color": "mottled green",
      "eye_color": "red",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 18
  },
  {
      "id": "33",
      "name": "Finis Valorum",
      "height": "170",
      "mass": "unknown",
      "hair_color": "blond",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "91BBY",
      "gender": "male",
      "planet": 9
  },
  {
      "id": "34",
      "name": "Padmé Amidala",
      "height": "185",
      "mass": "45",
      "hair_color": "brown",
      "skin_color": "light",
      "eye_color": "brown",
      "birth_year": "46BBY",
      "gender": "female",
      "planet": 8
  },
  {
      "id": "35",
      "name": "Jar Jar Binks",
      "height": "196",
      "mass": "66",
      "hair_color": "none",
      "skin_color": "orange",
      "eye_color": "orange",
      "birth_year": "52BBY",
      "gender": "male",
      "planet": 8
  },
  {
      "id": "36",
      "name": "Roos Tarpals",
      "height": "224",
      "mass": "82",
      "hair_color": "none",
      "skin_color": "grey",
      "eye_color": "orange",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 8
  },
  {
      "id": "37",
      "name": "Rugor Nass",
      "height": "206",
      "mass": "unknown",
      "hair_color": "none",
      "skin_color": "green",
      "eye_color": "orange",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 8
  },
  {
      "id": "38",
      "name": "Ric Olié",
      "height": "183",
      "mass": "unknown",
      "hair_color": "brown",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 8
  },
  {
      "id": "39",
      "name": "Watto",
      "height": "137",
      "mass": "unknown",
      "hair_color": "black",
      "skin_color": "blue, grey",
      "eye_color": "yellow",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 34
  },
  {
      "id": "40",
      "name": "Sebulba",
      "height": "112",
      "mass": "40",
      "hair_color": "none",
      "skin_color": "grey, red",
      "eye_color": "orange",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 35
  },
  {
      "id": "41",
      "name": "Quarsh Panaka",
      "height": "183",
      "mass": "unknown",
      "hair_color": "black",
      "skin_color": "dark",
      "eye_color": "brown",
      "birth_year": "62BBY",
      "gender": "male",
      "planet": 8
  },
  {
      "id": "42",
      "name": "Shmi Skywalker",
      "height": "163",
      "mass": "unknown",
      "hair_color": "black",
      "skin_color": "fair",
      "eye_color": "brown",
      "birth_year": "72BBY",
      "gender": "female",
      "planet": 1
  },
  {
      "id": "43",
      "name": "Darth Maul",
      "height": "175",
      "mass": "80",
      "hair_color": "none",
      "skin_color": "red",
      "eye_color": "yellow",
      "birth_year": "54BBY",
      "gender": "male",
      "planet": 36
  },
  {
      "id": "44",
      "name": "Bib Fortuna",
      "height": "180",
      "mass": "unknown",
      "hair_color": "none",
      "skin_color": "pale",
      "eye_color": "pink",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 37
  },
  {
      "id": "45",
      "name": "Ayla Secura",
      "height": "178",
      "mass": "55",
      "hair_color": "none",
      "skin_color": "blue",
      "eye_color": "hazel",
      "birth_year": "48BBY",
      "gender": "female",
      "planet": 37
  },
  {
      "id": "46",
      "name": "Ratts Tyerel",
      "height": "79",
      "mass": "15",
      "hair_color": "none",
      "skin_color": "grey, blue",
      "eye_color": "unknown",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 38
  },
  {
      "id": "47",
      "name": "Dud Bolt",
      "height": "94",
      "mass": "45",
      "hair_color": "none",
      "skin_color": "blue, grey",
      "eye_color": "yellow",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 39
  },
  {
      "id": "48",
      "name": "Gasgano",
      "height": "122",
      "mass": "unknown",
      "hair_color": "none",
      "skin_color": "white, blue",
      "eye_color": "black",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 40
  },
  {
      "id": "49",
      "name": "Ben Quadinaros",
      "height": "163",
      "mass": "65",
      "hair_color": "none",
      "skin_color": "grey, green, yellow",
      "eye_color": "orange",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 41
  },
  {
      "id": "50",
      "name": "Mace Windu",
      "height": "188",
      "mass": "84",
      "hair_color": "none",
      "skin_color": "dark",
      "eye_color": "brown",
      "birth_year": "72BBY",
      "gender": "male",
      "planet": 42
  },
  {
      "id": "51",
      "name": "Ki-Adi-Mundi",
      "height": "198",
      "mass": "82",
      "hair_color": "white",
      "skin_color": "pale",
      "eye_color": "yellow",
      "birth_year": "92BBY",
      "gender": "male",
      "planet": 43
  },
  {
      "id": "52",
      "name": "Kit Fisto",
      "height": "196",
      "mass": "87",
      "hair_color": "none",
      "skin_color": "green",
      "eye_color": "black",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 44
  },
  {
      "id": "53",
      "name": "Eeth Koth",
      "height": "171",
      "mass": "unknown",
      "hair_color": "black",
      "skin_color": "brown",
      "eye_color": "brown",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 45
  },
  {
      "id": "54",
      "name": "Adi Gallia",
      "height": "184",
      "mass": "50",
      "hair_color": "none",
      "skin_color": "dark",
      "eye_color": "blue",
      "birth_year": "unknown",
      "gender": "female",
      "planet": 9
  },
  {
      "id": "55",
      "name": "Saesee Tiin",
      "height": "188",
      "mass": "unknown",
      "hair_color": "none",
      "skin_color": "pale",
      "eye_color": "orange",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 47
  },
  {
      "id": "56",
      "name": "Yarael Poof",
      "height": "264",
      "mass": "unknown",
      "hair_color": "none",
      "skin_color": "white",
      "eye_color": "yellow",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 48
  },
  {
      "id": "57",
      "name": "Plo Koon",
      "height": "188",
      "mass": "80",
      "hair_color": "none",
      "skin_color": "orange",
      "eye_color": "black",
      "birth_year": "22BBY",
      "gender": "male",
      "planet": 49
  },
  {
      "id": "58",
      "name": "Mas Amedda",
      "height": "196",
      "mass": "unknown",
      "hair_color": "none",
      "skin_color": "blue",
      "eye_color": "blue",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 50
  },
  {
      "id": "59",
      "name": "Gregar Typho",
      "height": "185",
      "mass": "85",
      "hair_color": "black",
      "skin_color": "dark",
      "eye_color": "brown",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 8
  },
  {
      "id": "60",
      "name": "Cordé",
      "height": "157",
      "mass": "unknown",
      "hair_color": "brown",
      "skin_color": "light",
      "eye_color": "brown",
      "birth_year": "unknown",
      "gender": "female",
      "planet": 8
  },
  {
      "id": "61",
      "name": "Cliegg Lars",
      "height": "183",
      "mass": "unknown",
      "hair_color": "brown",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "82BBY",
      "gender": "male",
      "planet": 1
  },
  {
      "id": "62",
      "name": "Poggle the Lesser",
      "height": "183",
      "mass": "80",
      "hair_color": "none",
      "skin_color": "green",
      "eye_color": "yellow",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 11
  },
  {
      "id": "63",
      "name": "Luminara Unduli",
      "height": "170",
      "mass": "56.2",
      "hair_color": "black",
      "skin_color": "yellow",
      "eye_color": "blue",
      "birth_year": "58BBY",
      "gender": "female",
      "planet": 51
  },
  {
      "id": "64",
      "name": "Barriss Offee",
      "height": "166",
      "mass": "50",
      "hair_color": "black",
      "skin_color": "yellow",
      "eye_color": "blue",
      "birth_year": "40BBY",
      "gender": "female",
      "planet": 51
  },
  {
      "id": "65",
      "name": "Dormé",
      "height": "165",
      "mass": "unknown",
      "hair_color": "brown",
      "skin_color": "light",
      "eye_color": "brown",
      "birth_year": "unknown",
      "gender": "female",
      "planet": 8
  },
  {
      "id": "66",
      "name": "Dooku",
      "height": "193",
      "mass": "80",
      "hair_color": "white",
      "skin_color": "fair",
      "eye_color": "brown",
      "birth_year": "102BBY",
      "gender": "male",
      "planet": 52
  },
  {
      "id": "67",
      "name": "Bail Prestor Organa",
      "height": "191",
      "mass": "unknown",
      "hair_color": "black",
      "skin_color": "tan",
      "eye_color": "brown",
      "birth_year": "67BBY",
      "gender": "male",
      "planet": 2
  },
  {
      "id": "68",
      "name": "Jango Fett",
      "height": "183",
      "mass": "79",
      "hair_color": "black",
      "skin_color": "tan",
      "eye_color": "brown",
      "birth_year": "66BBY",
      "gender": "male",
      "planet": 53
  },
  {
      "id": "69",
      "name": "Zam Wesell",
      "height": "168",
      "mass": "55",
      "hair_color": "blonde",
      "skin_color": "fair, green, yellow",
      "eye_color": "yellow",
      "birth_year": "unknown",
      "gender": "female",
      "planet": 54
  },
  {
      "id": "70",
      "name": "Dexter Jettster",
      "height": "198",
      "mass": "102",
      "hair_color": "none",
      "skin_color": "brown",
      "eye_color": "yellow",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 55
  },
  {
      "id": "71",
      "name": "Lama Su",
      "height": "229",
      "mass": "88",
      "hair_color": "none",
      "skin_color": "grey",
      "eye_color": "black",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 10
  },
  {
      "id": "72",
      "name": "Taun We",
      "height": "213",
      "mass": "unknown",
      "hair_color": "none",
      "skin_color": "grey",
      "eye_color": "black",
      "birth_year": "unknown",
      "gender": "female",
      "planet": 10
  },
  {
      "id": "73",
      "name": "Jocasta Nu",
      "height": "167",
      "mass": "unknown",
      "hair_color": "white",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "unknown",
      "gender": "female",
      "planet": 9
  },
  {
      "id": "74",
      "name": "R4-P17",
      "height": "96",
      "mass": "unknown",
      "hair_color": "none",
      "skin_color": "silver, red",
      "eye_color": "red, blue",
      "birth_year": "unknown",
      "gender": "female",
      "planet": 28
  },
  {
      "id": "75",
      "name": "Wat Tambor",
      "height": "193",
      "mass": "48",
      "hair_color": "none",
      "skin_color": "green, grey",
      "eye_color": "unknown",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 56
  },
  {
      "id": "76",
      "name": "San Hill",
      "height": "191",
      "mass": "unknown",
      "hair_color": "none",
      "skin_color": "grey",
      "eye_color": "gold",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 57
  },
  {
      "id": "77",
      "name": "Shaak Ti",
      "height": "178",
      "mass": "57",
      "hair_color": "none",
      "skin_color": "red, blue, white",
      "eye_color": "black",
      "birth_year": "unknown",
      "gender": "female",
      "planet": 58
  },
  {
      "id": "78",
      "name": "Grievous",
      "height": "216",
      "mass": "159",
      "hair_color": "none",
      "skin_color": "brown, white",
      "eye_color": "green, yellow",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 59
  },
  {
      "id": "79",
      "name": "Tarfful",
      "height": "234",
      "mass": "136",
      "hair_color": "brown",
      "skin_color": "brown",
      "eye_color": "blue",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 14
  },
  {
      "id": "80",
      "name": "Raymus Antilles",
      "height": "188",
      "mass": "79",
      "hair_color": "brown",
      "skin_color": "light",
      "eye_color": "brown",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 2
  },
  {
      "id": "81",
      "name": "Sly Moore",
      "height": "178",
      "mass": "48",
      "hair_color": "none",
      "skin_color": "pale",
      "eye_color": "white",
      "birth_year": "unknown",
      "gender": "female",
      "planet": 60
  },
  {
      "id": "82",
      "name": "Tion Medon",
      "height": "206",
      "mass": "80",
      "hair_color": "none",
      "skin_color": "grey",
      "eye_color": "black",
      "birth_year": "unknown",
      "gender": "male",
      "planet": 12
  }
]

const planet = [
  {
      "id": "1",
      "climate": "arid",
      "surface_water": "1",
      "name": "Tatooine",
      "diameter": "10465",
      "rotation_period": "23",
      "terrain": "desert",
      "gravity": "1 standard",
      "orbital_period": "304",
      "population": "200000"
  },
  {
      "id": "2",
      "climate": "temperate",
      "surface_water": "40",
      "name": "Alderaan",
      "diameter": "12500",
      "rotation_period": "24",
      "terrain": "grasslands, mountains",
      "gravity": "1 standard",
      "orbital_period": "364",
      "population": "2000000000"
  },
  {
      "id": "3",
      "climate": "temperate, tropical",
      "surface_water": "8",
      "name": "Yavin IV",
      "diameter": "10200",
      "rotation_period": "24",
      "terrain": "jungle, rainforests",
      "gravity": "1 standard",
      "orbital_period": "4818",
      "population": "1000"
  },
  {
      "id": "4",
      "climate": "frozen",
      "surface_water": "100",
      "name": "Hoth",
      "diameter": "7200",
      "rotation_period": "23",
      "terrain": "tundra, ice caves, mountain ranges",
      "gravity": "1.1 standard",
      "orbital_period": "549",
      "population": "unknown"
  },
  {
      "id": "5",
      "climate": "murky",
      "surface_water": "8",
      "name": "Dagobah",
      "diameter": "8900",
      "rotation_period": "23",
      "terrain": "swamp, jungles",
      "gravity": "N/A",
      "orbital_period": "341",
      "population": "unknown"
  },
  {
      "id": "6",
      "climate": "temperate",
      "surface_water": "0",
      "name": "Bespin",
      "diameter": "118000",
      "rotation_period": "12",
      "terrain": "gas giant",
      "gravity": "1.5 (surface), 1 standard (Cloud City)",
      "orbital_period": "5110",
      "population": "6000000"
  },
  {
      "id": "7",
      "climate": "temperate",
      "surface_water": "8",
      "name": "Endor",
      "diameter": "4900",
      "rotation_period": "18",
      "terrain": "forests, mountains, lakes",
      "gravity": "0.85 standard",
      "orbital_period": "402",
      "population": "30000000"
  },
  {
      "id": "8",
      "climate": "temperate",
      "surface_water": "12",
      "name": "Naboo",
      "diameter": "12120",
      "rotation_period": "26",
      "terrain": "grassy hills, swamps, forests, mountains",
      "gravity": "1 standard",
      "orbital_period": "312",
      "population": "4500000000"
  },
  {
      "id": "9",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Coruscant",
      "diameter": "12240",
      "rotation_period": "24",
      "terrain": "cityscape, mountains",
      "gravity": "1 standard",
      "orbital_period": "368",
      "population": "1000000000000"
  },
  {
      "id": "10",
      "climate": "temperate",
      "surface_water": "100",
      "name": "Kamino",
      "diameter": "19720",
      "rotation_period": "27",
      "terrain": "ocean",
      "gravity": "1 standard",
      "orbital_period": "463",
      "population": "1000000000"
  },
  {
      "id": "11",
      "climate": "temperate, arid",
      "surface_water": "5",
      "name": "Geonosis",
      "diameter": "11370",
      "rotation_period": "30",
      "terrain": "rock, desert, mountain, barren",
      "gravity": "0.9 standard",
      "orbital_period": "256",
      "population": "100000000000"
  },
  {
      "id": "12",
      "climate": "temperate, arid, windy",
      "surface_water": "0.9",
      "name": "Utapau",
      "diameter": "12900",
      "rotation_period": "27",
      "terrain": "scrublands, savanna, canyons, sinkholes",
      "gravity": "1 standard",
      "orbital_period": "351",
      "population": "95000000"
  },
  {
      "id": "13",
      "climate": "hot",
      "surface_water": "0",
      "name": "Mustafar",
      "diameter": "4200",
      "rotation_period": "36",
      "terrain": "volcanoes, lava rivers, mountains, caves",
      "gravity": "1 standard",
      "orbital_period": "412",
      "population": "20000"
  },
  {
      "id": "14",
      "climate": "tropical",
      "surface_water": "60",
      "name": "Kashyyyk",
      "diameter": "12765",
      "rotation_period": "26",
      "terrain": "jungle, forests, lakes, rivers",
      "gravity": "1 standard",
      "orbital_period": "381",
      "population": "45000000"
  },
  {
      "id": "15",
      "climate": "artificial temperate ",
      "surface_water": "0",
      "name": "Polis Massa",
      "diameter": "0",
      "rotation_period": "24",
      "terrain": "airless asteroid",
      "gravity": "0.56 standard",
      "orbital_period": "590",
      "population": "1000000"
  },
  {
      "id": "16",
      "climate": "frigid",
      "surface_water": "unknown",
      "name": "Mygeeto",
      "diameter": "10088",
      "rotation_period": "12",
      "terrain": "glaciers, mountains, ice canyons",
      "gravity": "1 standard",
      "orbital_period": "167",
      "population": "19000000"
  },
  {
      "id": "17",
      "climate": "hot, humid",
      "surface_water": "unknown",
      "name": "Felucia",
      "diameter": "9100",
      "rotation_period": "34",
      "terrain": "fungus forests",
      "gravity": "0.75 standard",
      "orbital_period": "231",
      "population": "8500000"
  },
  {
      "id": "18",
      "climate": "temperate, moist",
      "surface_water": "unknown",
      "name": "Cato Neimoidia",
      "diameter": "0",
      "rotation_period": "25",
      "terrain": "mountains, fields, forests, rock arches",
      "gravity": "1 standard",
      "orbital_period": "278",
      "population": "10000000"
  },
  {
      "id": "19",
      "climate": "hot",
      "surface_water": "unknown",
      "name": "Saleucami",
      "diameter": "14920",
      "rotation_period": "26",
      "terrain": "caves, desert, mountains, volcanoes",
      "gravity": "unknown",
      "orbital_period": "392",
      "population": "1400000000"
  },
  {
      "id": "20",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Stewjon",
      "diameter": "0",
      "rotation_period": "unknown",
      "terrain": "grass",
      "gravity": "1 standard",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "21",
      "climate": "polluted",
      "surface_water": "unknown",
      "name": "Eriadu",
      "diameter": "13490",
      "rotation_period": "24",
      "terrain": "cityscape",
      "gravity": "1 standard",
      "orbital_period": "360",
      "population": "22000000000"
  },
  {
      "id": "22",
      "climate": "temperate",
      "surface_water": "70",
      "name": "Corellia",
      "diameter": "11000",
      "rotation_period": "25",
      "terrain": "plains, urban, hills, forests",
      "gravity": "1 standard",
      "orbital_period": "329",
      "population": "3000000000"
  },
  {
      "id": "23",
      "climate": "hot",
      "surface_water": "60",
      "name": "Rodia",
      "diameter": "7549",
      "rotation_period": "29",
      "terrain": "jungles, oceans, urban, swamps",
      "gravity": "1 standard",
      "orbital_period": "305",
      "population": "1300000000"
  },
  {
      "id": "24",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Nal Hutta",
      "diameter": "12150",
      "rotation_period": "87",
      "terrain": "urban, oceans, swamps, bogs",
      "gravity": "1 standard",
      "orbital_period": "413",
      "population": "7000000000"
  },
  {
      "id": "25",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Dantooine",
      "diameter": "9830",
      "rotation_period": "25",
      "terrain": "oceans, savannas, mountains, grasslands",
      "gravity": "1 standard",
      "orbital_period": "378",
      "population": "1000"
  },
  {
      "id": "26",
      "climate": "temperate",
      "surface_water": "98",
      "name": "Bestine IV",
      "diameter": "6400",
      "rotation_period": "26",
      "terrain": "rocky islands, oceans",
      "gravity": "unknown",
      "orbital_period": "680",
      "population": "62000000"
  },
  {
      "id": "27",
      "climate": "temperate",
      "surface_water": "10",
      "name": "Ord Mantell",
      "diameter": "14050",
      "rotation_period": "26",
      "terrain": "plains, seas, mesas",
      "gravity": "1 standard",
      "orbital_period": "334",
      "population": "4000000000"
  },
  {
      "id": "28",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "unknown",
      "diameter": "0",
      "rotation_period": "0",
      "terrain": "unknown",
      "gravity": "unknown",
      "orbital_period": "0",
      "population": "unknown"
  },
  {
      "id": "29",
      "climate": "arid",
      "surface_water": "unknown",
      "name": "Trandosha",
      "diameter": "0",
      "rotation_period": "25",
      "terrain": "mountains, seas, grasslands, deserts",
      "gravity": "0.62 standard",
      "orbital_period": "371",
      "population": "42000000"
  },
  {
      "id": "30",
      "climate": "arid",
      "surface_water": "unknown",
      "name": "Socorro",
      "diameter": "0",
      "rotation_period": "20",
      "terrain": "deserts, mountains",
      "gravity": "1 standard",
      "orbital_period": "326",
      "population": "300000000"
  },
  {
      "id": "31",
      "climate": "temperate",
      "surface_water": "100",
      "name": "Mon Cala",
      "diameter": "11030",
      "rotation_period": "21",
      "terrain": "oceans, reefs, islands",
      "gravity": "1",
      "orbital_period": "398",
      "population": "27000000000"
  },
  {
      "id": "32",
      "climate": "temperate",
      "surface_water": "40",
      "name": "Chandrila",
      "diameter": "13500",
      "rotation_period": "20",
      "terrain": "plains, forests",
      "gravity": "1",
      "orbital_period": "368",
      "population": "1200000000"
  },
  {
      "id": "33",
      "climate": "superheated",
      "surface_water": "5",
      "name": "Sullust",
      "diameter": "12780",
      "rotation_period": "20",
      "terrain": "mountains, volcanoes, rocky deserts",
      "gravity": "1",
      "orbital_period": "263",
      "population": "18500000000"
  },
  {
      "id": "34",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Toydaria",
      "diameter": "7900",
      "rotation_period": "21",
      "terrain": "swamps, lakes",
      "gravity": "1",
      "orbital_period": "184",
      "population": "11000000"
  },
  {
      "id": "35",
      "climate": "arid, temperate, tropical",
      "surface_water": "unknown",
      "name": "Malastare",
      "diameter": "18880",
      "rotation_period": "26",
      "terrain": "swamps, deserts, jungles, mountains",
      "gravity": "1.56",
      "orbital_period": "201",
      "population": "2000000000"
  },
  {
      "id": "36",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Dathomir",
      "diameter": "10480",
      "rotation_period": "24",
      "terrain": "forests, deserts, savannas",
      "gravity": "0.9",
      "orbital_period": "491",
      "population": "5200"
  },
  {
      "id": "37",
      "climate": "temperate, arid, subartic",
      "surface_water": "5",
      "name": "Ryloth",
      "diameter": "10600",
      "rotation_period": "30",
      "terrain": "mountains, valleys, deserts, tundra",
      "gravity": "1",
      "orbital_period": "305",
      "population": "1500000000"
  },
  {
      "id": "38",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Aleen Minor",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "unknown",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "39",
      "climate": "temperate, artic",
      "surface_water": "unknown",
      "name": "Vulpter",
      "diameter": "14900",
      "rotation_period": "22",
      "terrain": "urban, barren",
      "gravity": "1",
      "orbital_period": "391",
      "population": "421000000"
  },
  {
      "id": "40",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Troiken",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "desert, tundra, rainforests, mountains",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "41",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Tund",
      "diameter": "12190",
      "rotation_period": "48",
      "terrain": "barren, ash",
      "gravity": "unknown",
      "orbital_period": "1770",
      "population": "0"
  },
  {
      "id": "42",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Haruun Kal",
      "diameter": "10120",
      "rotation_period": "25",
      "terrain": "toxic cloudsea, plateaus, volcanoes",
      "gravity": "0.98",
      "orbital_period": "383",
      "population": "705300"
  },
  {
      "id": "43",
      "climate": "temperate",
      "surface_water": "20",
      "name": "Cerea",
      "diameter": "unknown",
      "rotation_period": "27",
      "terrain": "verdant",
      "gravity": "1",
      "orbital_period": "386",
      "population": "450000000"
  },
  {
      "id": "44",
      "climate": "tropical, temperate",
      "surface_water": "80",
      "name": "Glee Anselm",
      "diameter": "15600",
      "rotation_period": "33",
      "terrain": "lakes, islands, swamps, seas",
      "gravity": "1",
      "orbital_period": "206",
      "population": "500000000"
  },
  {
      "id": "45",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Iridonia",
      "diameter": "unknown",
      "rotation_period": "29",
      "terrain": "rocky canyons, acid pools",
      "gravity": "unknown",
      "orbital_period": "413",
      "population": "unknown"
  },
  {
      "id": "46",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Tholoth",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "unknown",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "47",
      "climate": "arid, rocky, windy",
      "surface_water": "unknown",
      "name": "Iktotch",
      "diameter": "unknown",
      "rotation_period": "22",
      "terrain": "rocky",
      "gravity": "1",
      "orbital_period": "481",
      "population": "unknown"
  },
  {
      "id": "48",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Quermia",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "unknown",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "49",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Dorin",
      "diameter": "13400",
      "rotation_period": "22",
      "terrain": "unknown",
      "gravity": "1",
      "orbital_period": "409",
      "population": "unknown"
  },
  {
      "id": "50",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Champala",
      "diameter": "unknown",
      "rotation_period": "27",
      "terrain": "oceans, rainforests, plateaus",
      "gravity": "1",
      "orbital_period": "318",
      "population": "3500000000"
  },
  {
      "id": "51",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Mirial",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "deserts",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "52",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Serenno",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "rainforests, rivers, mountains",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "53",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Concord Dawn",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "jungles, forests, deserts",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "54",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Zolan",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "unknown",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "55",
      "climate": "frigid",
      "surface_water": "100",
      "name": "Ojom",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "oceans, glaciers",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "500000000"
  },
  {
      "id": "56",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Skako",
      "diameter": "unknown",
      "rotation_period": "27",
      "terrain": "urban, vines",
      "gravity": "1",
      "orbital_period": "384",
      "population": "500000000000"
  },
  {
      "id": "57",
      "climate": "temperate",
      "surface_water": "25",
      "name": "Muunilinst",
      "diameter": "13800",
      "rotation_period": "28",
      "terrain": "plains, forests, hills, mountains",
      "gravity": "1",
      "orbital_period": "412",
      "population": "5000000000"
  },
  {
      "id": "58",
      "climate": "temperate",
      "surface_water": "unknown",
      "name": "Shili",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "cities, savannahs, seas, plains",
      "gravity": "1",
      "orbital_period": "unknown",
      "population": "unknown"
  },
  {
      "id": "59",
      "climate": "arid, temperate, tropical",
      "surface_water": "unknown",
      "name": "Kalee",
      "diameter": "13850",
      "rotation_period": "23",
      "terrain": "rainforests, cliffs, canyons, seas",
      "gravity": "1",
      "orbital_period": "378",
      "population": "4000000000"
  },
  {
      "id": "60",
      "climate": "unknown",
      "surface_water": "unknown",
      "name": "Umbara",
      "diameter": "unknown",
      "rotation_period": "unknown",
      "terrain": "unknown",
      "gravity": "unknown",
      "orbital_period": "unknown",
      "population": "unknown"
  }
]

const specie = [
  {
      "id": "1",
      "classification": "mammal",
      "name": "Human",
      "designation": "sentient",
      "eye_colors": "brown, blue, green, hazel, grey, amber",
      "people": [
          66,
          67,
          68,
          74
      ],
      "skin_colors": "caucasian, black, asian, hispanic",
      "language": "Galactic Basic",
      "hair_colors": "blonde, brown, black, red",
      "homeworld": 9,
      "average_lifespan": "120",
      "average_height": "180"
  },
  {
      "id": "2",
      "classification": "artificial",
      "name": "Droid",
      "designation": "sentient",
      "eye_colors": "n/a",
      "people": [
          2,
          3,
          8,
          23
      ],
      "skin_colors": "n/a",
      "language": "n/a",
      "hair_colors": "n/a",
      "homeworld": null,
      "average_lifespan": "indefinite",
      "average_height": "n/a"
  },
  {
      "id": "3",
      "classification": "mammal",
      "name": "Wookie",
      "designation": "sentient",
      "eye_colors": "blue, green, yellow, brown, golden, red",
      "people": [
          13,
          80
      ],
      "skin_colors": "gray",
      "language": "Shyriiwook",
      "hair_colors": "black, brown",
      "homeworld": 14,
      "average_lifespan": "400",
      "average_height": "210"
  },
  {
      "id": "4",
      "classification": "sentient",
      "name": "Rodian",
      "designation": "reptilian",
      "eye_colors": "black",
      "people": [
          15
      ],
      "skin_colors": "green, blue",
      "language": "Galatic Basic",
      "hair_colors": "n/a",
      "homeworld": 23,
      "average_lifespan": "unknown",
      "average_height": "170"
  },
  {
      "id": "5",
      "classification": "gastropod",
      "name": "Hutt",
      "designation": "sentient",
      "eye_colors": "yellow, red",
      "people": [
          16
      ],
      "skin_colors": "green, brown, tan",
      "language": "Huttese",
      "hair_colors": "n/a",
      "homeworld": 24,
      "average_lifespan": "1000",
      "average_height": "300"
  },
  {
      "id": "6",
      "classification": "mammal",
      "name": "Yoda's species",
      "designation": "sentient",
      "eye_colors": "brown, green, yellow",
      "people": [
          20
      ],
      "skin_colors": "green, yellow",
      "language": "Galactic basic",
      "hair_colors": "brown, white",
      "homeworld": 28,
      "average_lifespan": "900",
      "average_height": "66"
  },
  {
      "id": "7",
      "classification": "reptile",
      "name": "Trandoshan",
      "designation": "sentient",
      "eye_colors": "yellow, orange",
      "people": [
          24
      ],
      "skin_colors": "brown, green",
      "language": "Dosh",
      "hair_colors": "none",
      "homeworld": 29,
      "average_lifespan": "unknown",
      "average_height": "200"
  },
  {
      "id": "8",
      "classification": "amphibian",
      "name": "Mon Calamari",
      "designation": "sentient",
      "eye_colors": "yellow",
      "people": [
          27
      ],
      "skin_colors": "red, blue, brown, magenta",
      "language": "Mon Calamarian",
      "hair_colors": "none",
      "homeworld": 31,
      "average_lifespan": "unknown",
      "average_height": "160"
  },
  {
      "id": "9",
      "classification": "mammal",
      "name": "Ewok",
      "designation": "sentient",
      "eye_colors": "orange, brown",
      "people": [
          30
      ],
      "skin_colors": "brown",
      "language": "Ewokese",
      "hair_colors": "white, brown, black",
      "homeworld": 7,
      "average_lifespan": "unknown",
      "average_height": "100"
  },
  {
      "id": "10",
      "classification": "mammal",
      "name": "Sullustan",
      "designation": "sentient",
      "eye_colors": "black",
      "people": [
          31
      ],
      "skin_colors": "pale",
      "language": "Sullutese",
      "hair_colors": "none",
      "homeworld": 33,
      "average_lifespan": "unknown",
      "average_height": "180"
  },
  {
      "id": "11",
      "classification": "unknown",
      "name": "Neimodian",
      "designation": "sentient",
      "eye_colors": "red, pink",
      "people": [
          33
      ],
      "skin_colors": "grey, green",
      "language": "Neimoidia",
      "hair_colors": "none",
      "homeworld": 18,
      "average_lifespan": "unknown",
      "average_height": "180"
  },
  {
      "id": "12",
      "classification": "amphibian",
      "name": "Gungan",
      "designation": "sentient",
      "eye_colors": "orange",
      "people": [
          36,
          37,
          38
      ],
      "skin_colors": "brown, green",
      "language": "Gungan basic",
      "hair_colors": "none",
      "homeworld": 8,
      "average_lifespan": "unknown",
      "average_height": "190"
  },
  {
      "id": "13",
      "classification": "mammal",
      "name": "Toydarian",
      "designation": "sentient",
      "eye_colors": "yellow",
      "people": [
          40
      ],
      "skin_colors": "blue, green, grey",
      "language": "Toydarian",
      "hair_colors": "none",
      "homeworld": 34,
      "average_lifespan": "91",
      "average_height": "120"
  },
  {
      "id": "14",
      "classification": "mammal",
      "name": "Dug",
      "designation": "sentient",
      "eye_colors": "yellow, blue",
      "people": [
          41
      ],
      "skin_colors": "brown, purple, grey, red",
      "language": "Dugese",
      "hair_colors": "none",
      "homeworld": 35,
      "average_lifespan": "unknown",
      "average_height": "100"
  },
  {
      "id": "15",
      "classification": "mammals",
      "name": "Twi'lek",
      "designation": "sentient",
      "eye_colors": "blue, brown, orange, pink",
      "people": [
          45,
          46
      ],
      "skin_colors": "orange, yellow, blue, green, pink, purple, tan",
      "language": "Twi'leki",
      "hair_colors": "none",
      "homeworld": 37,
      "average_lifespan": "unknown",
      "average_height": "200"
  },
  {
      "id": "16",
      "classification": "reptile",
      "name": "Aleena",
      "designation": "sentient",
      "eye_colors": "unknown",
      "people": [
          47
      ],
      "skin_colors": "blue, gray",
      "language": "Aleena",
      "hair_colors": "none",
      "homeworld": 38,
      "average_lifespan": "79",
      "average_height": "80"
  },
  {
      "id": "17",
      "classification": "unknown",
      "name": "Vulptereen",
      "designation": "sentient",
      "eye_colors": "yellow",
      "people": [
          48
      ],
      "skin_colors": "grey",
      "language": "vulpterish",
      "hair_colors": "none",
      "homeworld": 39,
      "average_lifespan": "unknown",
      "average_height": "100"
  },
  {
      "id": "18",
      "classification": "unknown",
      "name": "Xexto",
      "designation": "sentient",
      "eye_colors": "black",
      "people": [
          49
      ],
      "skin_colors": "grey, yellow, purple",
      "language": "Xextese",
      "hair_colors": "none",
      "homeworld": 40,
      "average_lifespan": "unknown",
      "average_height": "125"
  },
  {
      "id": "19",
      "classification": "unknown",
      "name": "Toong",
      "designation": "sentient",
      "eye_colors": "orange",
      "people": [
          50
      ],
      "skin_colors": "grey, green, yellow",
      "language": "Tundan",
      "hair_colors": "none",
      "homeworld": 41,
      "average_lifespan": "unknown",
      "average_height": "200"
  },
  {
      "id": "20",
      "classification": "mammal",
      "name": "Cerean",
      "designation": "sentient",
      "eye_colors": "hazel",
      "people": [
          52
      ],
      "skin_colors": "pale pink",
      "language": "Cerean",
      "hair_colors": "red, blond, black, white",
      "homeworld": 43,
      "average_lifespan": "unknown",
      "average_height": "200"
  },
  {
      "id": "21",
      "classification": "amphibian",
      "name": "Nautolan",
      "designation": "sentient",
      "eye_colors": "black",
      "people": [
          53
      ],
      "skin_colors": "green, blue, brown, red",
      "language": "Nautila",
      "hair_colors": "none",
      "homeworld": 44,
      "average_lifespan": "70",
      "average_height": "180"
  },
  {
      "id": "22",
      "classification": "mammal",
      "name": "Zabrak",
      "designation": "sentient",
      "eye_colors": "brown, orange",
      "people": [
          44,
          54
      ],
      "skin_colors": "pale, brown, red, orange, yellow",
      "language": "Zabraki",
      "hair_colors": "black",
      "homeworld": 45,
      "average_lifespan": "unknown",
      "average_height": "180"
  },
  {
      "id": "23",
      "classification": "mammal",
      "name": "Tholothian",
      "designation": "sentient",
      "eye_colors": "blue, indigo",
      "people": [
          55
      ],
      "skin_colors": "dark",
      "language": "unknown",
      "hair_colors": "unknown",
      "homeworld": 46,
      "average_lifespan": "unknown",
      "average_height": "unknown"
  },
  {
      "id": "24",
      "classification": "unknown",
      "name": "Iktotchi",
      "designation": "sentient",
      "eye_colors": "orange",
      "people": [
          56
      ],
      "skin_colors": "pink",
      "language": "Iktotchese",
      "hair_colors": "none",
      "homeworld": 47,
      "average_lifespan": "unknown",
      "average_height": "180"
  },
  {
      "id": "25",
      "classification": "mammal",
      "name": "Quermian",
      "designation": "sentient",
      "eye_colors": "yellow",
      "people": [
          57
      ],
      "skin_colors": "white",
      "language": "Quermian",
      "hair_colors": "none",
      "homeworld": 48,
      "average_lifespan": "86",
      "average_height": "240"
  },
  {
      "id": "26",
      "classification": "unknown",
      "name": "Kel Dor",
      "designation": "sentient",
      "eye_colors": "black, silver",
      "people": [
          58
      ],
      "skin_colors": "peach, orange, red",
      "language": "Kel Dor",
      "hair_colors": "none",
      "homeworld": 49,
      "average_lifespan": "70",
      "average_height": "180"
  },
  {
      "id": "27",
      "classification": "amphibian",
      "name": "Chagrian",
      "designation": "sentient",
      "eye_colors": "blue",
      "people": [
          59
      ],
      "skin_colors": "blue",
      "language": "Chagria",
      "hair_colors": "none",
      "homeworld": 50,
      "average_lifespan": "unknown",
      "average_height": "190"
  },
  {
      "id": "28",
      "classification": "insectoid",
      "name": "Geonosian",
      "designation": "sentient",
      "eye_colors": "green, hazel",
      "people": [
          63
      ],
      "skin_colors": "green, brown",
      "language": "Geonosian",
      "hair_colors": "none",
      "homeworld": 11,
      "average_lifespan": "unknown",
      "average_height": "178"
  },
  {
      "id": "29",
      "classification": "mammal",
      "name": "Mirialan",
      "designation": "sentient",
      "eye_colors": "blue, green, red, yellow, brown, orange",
      "people": [
          64,
          65
      ],
      "skin_colors": "yellow, green",
      "language": "Mirialan",
      "hair_colors": "black, brown",
      "homeworld": 51,
      "average_lifespan": "unknown",
      "average_height": "180"
  },
  {
      "id": "30",
      "classification": "reptilian",
      "name": "Clawdite",
      "designation": "sentient",
      "eye_colors": "yellow",
      "people": [
          70
      ],
      "skin_colors": "green, yellow",
      "language": "Clawdite",
      "hair_colors": "none",
      "homeworld": 54,
      "average_lifespan": "70",
      "average_height": "180"
  },
  {
      "id": "31",
      "classification": "amphibian",
      "name": "Besalisk",
      "designation": "sentient",
      "eye_colors": "yellow",
      "people": [
          71
      ],
      "skin_colors": "brown",
      "language": "besalisk",
      "hair_colors": "none",
      "homeworld": 55,
      "average_lifespan": "75",
      "average_height": "178"
  },
  {
      "id": "32",
      "classification": "amphibian",
      "name": "Kaminoan",
      "designation": "sentient",
      "eye_colors": "black",
      "people": [
          72,
          73
      ],
      "skin_colors": "grey, blue",
      "language": "Kaminoan",
      "hair_colors": "none",
      "homeworld": 10,
      "average_lifespan": "80",
      "average_height": "220"
  },
  {
      "id": "33",
      "classification": "mammal",
      "name": "Skakoan",
      "designation": "sentient",
      "eye_colors": "unknown",
      "people": [
          76
      ],
      "skin_colors": "grey, green",
      "language": "Skakoan",
      "hair_colors": "none",
      "homeworld": 56,
      "average_lifespan": "unknown",
      "average_height": "unknown"
  },
  {
      "id": "34",
      "classification": "mammal",
      "name": "Muun",
      "designation": "sentient",
      "eye_colors": "black",
      "people": [
          77
      ],
      "skin_colors": "grey, white",
      "language": "Muun",
      "hair_colors": "none",
      "homeworld": 57,
      "average_lifespan": "100",
      "average_height": "190"
  },
  {
      "id": "35",
      "classification": "mammal",
      "name": "Togruta",
      "designation": "sentient",
      "eye_colors": "red, orange, yellow, green, blue, black",
      "people": [
          78
      ],
      "skin_colors": "red, white, orange, yellow, green, blue",
      "language": "Togruti",
      "hair_colors": "none",
      "homeworld": 58,
      "average_lifespan": "94",
      "average_height": "180"
  },
  {
      "id": "36",
      "classification": "reptile",
      "name": "Kaleesh",
      "designation": "sentient",
      "eye_colors": "yellow",
      "people": [
          79
      ],
      "skin_colors": "brown, orange, tan",
      "language": "Kaleesh",
      "hair_colors": "none",
      "homeworld": 59,
      "average_lifespan": "80",
      "average_height": "170"
  },
  {
      "id": "37",
      "classification": "mammal",
      "name": "Pau'an",
      "designation": "sentient",
      "eye_colors": "black",
      "people": [
          83
      ],
      "skin_colors": "grey",
      "language": "Utapese",
      "hair_colors": "none",
      "homeworld": 12,
      "average_lifespan": "700",
      "average_height": "190"
  }
]

// Using CommonJS style export so we can consume via Node (without using Babel-node)
module.exports = {
  starship,
  people,
  planet
};
